pub enum AddrMode {
    AmImp,
    AmRD16,
    AmRr,
    AmMrr,
    AmR,
    AmRD8,
    AmRMr,
    AmRhli,
    AmRhld,
    AmHlir,
    AmHldr,
    AmRa8,
    AmA8r,
    AmHlspr,
    AmD16,
    AmD8,
    AmD16r,
    AmMrd8,
    AmMr,
    AmA16r,
    AmRa16,
}

pub enum RegType {
    RtNone,
    RtA,
    RtF,
    RtB,
    RtC,
    RtD,
    RtE,
    RtH,
    RtL,
    RtAf,
    RtBc,
    RtDe,
    RtHl,
    RtSp,
    RtPc,
}

pub enum InType {
    InNone,
    InNop,
    InLd,
    InInc,
    InDec,
    InRlca,
    InAdd,
    InRrca,
    InStop,
    InRla,
    InJr,
    InRra,
    InDaa,
    InCpl,
    InScf,
    InCcf,
    InHalt,
    InAdc,
    InSub,
    InSbc,
    InAnd,
    InXor,
    InOr,
    InCp,
    InPop,
    InJp,
    InPush,
    InRet,
    InCb,
    InCall,
    InReti,
    InLdh,
    InJphl,
    InDi,
    InEi,
    InRst,
    InErr,
    //CB instructions...
    InRlc,
    InRrc,
    InRl,
    InRr,
    InSla,
    InSra,
    InSwap,
    InSrl,
    InBit,
    InRes,
    InSet,
}

pub enum CondType {
    CtNone,
    CtNz,
    CtZ,
    CtNc,
    CtC,
}

pub struct Instruction {
    pub type_in: InType,
    pub mode: AddrMode,
    pub reg_1: RegType,
    pub reg_2: RegType,
    pub cond: CondType,
    pub param: u8,
}

pub fn instruction_by_opcode(opcode: u8) -> Option<Instruction> {
    match opcode {
        0x00 => Some(Instruction {
            type_in: InType::InNop,
            mode: AddrMode::AmImp,
            reg_1: RegType::RtNone,
            reg_2: RegType::RtNone,
            cond: CondType::CtNone,
            param: 0,
        }),
        0x05 => Some(Instruction {
            type_in: InType::InDec,
            mode: AddrMode::AmR,
            reg_1: RegType::RtB,
            reg_2: RegType::RtNone,
            cond: CondType::CtNone,
            param: 0,
        }),
        0x0E => Some(Instruction {
            type_in: InType::InLd,
            mode: AddrMode::AmRD8,
            reg_1: RegType::RtC,
            reg_2: RegType::RtNone,
            cond: CondType::CtNone,
            param: 0,
        }),
        0xAF => Some(Instruction {
            type_in: InType::InXor,
            mode: AddrMode::AmR,
            reg_1: RegType::RtA,
            reg_2: RegType::RtNone,
            cond: CondType::CtNone,
            param: 0,
        }),
        0xC3 => Some(Instruction {
            type_in: InType::InJp,
            mode: AddrMode::AmD16,
            reg_1: RegType::RtNone,
            reg_2: RegType::RtNone,
            cond: CondType::CtNone,
            param: 0,
        }),
        0xF3 => Some(Instruction {
            type_in: InType::InDi,
            mode: AddrMode::AmImp,
            reg_1: RegType::RtNone,
            reg_2: RegType::RtNone,
            cond: CondType::CtNone,
            param: 0,
        }),
        _ => None,
    }
}
